### ISSUE TITLE
Apparaat Onbeschikbaar Sensor data ontbreekt: sound

### ISSUE THREAD

**Issue by hans-github** [jghaanstra/android.ipwebcam#12]
Connection fails despite IP Webcam Settings: "Enable sound detection", and "Audio mode"="Enabled".

**Comment by jghaanstra** [comment]
This mostly happens because the setup instructions from the first post in the support topic have not been followed correctly or the device is missing a sensor needed for this app to function. If you are 100% sure you have followed the instructions correctly you can post the output of http://<<your_ip_webcamip>>:<<ip_webcam_port>>/sensors.json here and  I’ll have a look what is going on.

**Comment by hans-github** [comment]
Ah, thanks. More sensors had to be enabled.
